name: Build Windows Application

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore UtilityDocuments.csproj -r win-x86

      # 4. Publish the WPF application
      - name: Publish the application
        run: dotnet publish UtilityDocuments.csproj --configuration Release --no-restore --self-contained true -r win-x86

      # --- Steps for main branch (Installer) ---
      - name: Install WiX Toolset
        if: github.ref == 'refs/heads/main'
        run: |
          $msi = "$env:USERPROFILE\wix-cli-x64.msi"
          Invoke-WebRequest -Uri "https://github.com/wixtoolset/wix/releases/download/v6.0.2/wix-cli-x64.msi" -OutFile $msi
          Start-Process msiexec.exe -ArgumentList "/i `"$msi`" /quiet /norestart" -Wait
          $env:PATH += ";C:\Program Files (x86)\WiX Toolset v6\bin"

      - name: Build MSI installer
        if: github.ref == 'refs/heads/main'
        run: |
          $sourceDir = "$(pwd)\bin\Release\net8.0-windows\win-x86\publish"
          $wixObj = "Setup\setup.wixobj"
          $msiOut = "Setup\bin\Release\UtilityDocuments.msi"
          candle.exe -dSourceDir=$sourceDir Setup\setup.wxs -out $wixObj
          light.exe $wixObj -out $msiOut

      - name: Upload Artifacts (MSI)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Setup/bin/Release/**/*.msi

      # --- Steps for other branches (ZIP) ---
      - name: Package application artifacts (ZIP)
        if: github.ref != 'refs/heads/main'
        run: |
          $sourceDir = "bin/Release/net8.0-windows/win-x86/publish"
          Compress-Archive -Path "$sourceDir\*" -DestinationPath "UtilityDocuments.zip"

      - name: Upload Artifacts (ZIP)
        if: github.ref != 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: windows-application-zip
          path: ./*.zip

  create-release-on-tag:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: artifacts

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release generated by CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload MSI to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: artifacts/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
