name: Build Windows App and MSI Installer

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Download and setup WiX 4
      - name: Download and setup WiX 4
        run: |
          $url = "https://github.com/wixtoolset/wix4/releases/download/v4.0.1/wix311-binaries.zip"
          $zip = "$env:USERPROFILE\wix.zip"
          $dest = "$env:USERPROFILE\wix"
          Invoke-WebRequest -Uri $url -OutFile $zip
          Expand-Archive -Path $zip -DestinationPath $dest
          $env:PATH += ";$dest\bin"

      # 4. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore UtilityDocuments.csproj

      # 5. Build the WPF application
      - name: Build the application
        run: dotnet build UtilityDocuments.csproj --configuration Release --no-restore

      # 6. Build the MSI installer
      - name: Build the MSI installer
        run: dotnet build Setup/setup.wixproj --configuration Release

      # 7. List build artifacts for debugging
      - name: List build artifacts
        run: Get-ChildItem -Recurse .\bin, .\Setup\bin | Select-Object FullName, Length

      # 8. Upload MSI artifact
      - name: Upload Artifacts (MSI)
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: Setup/bin/Release/**/*.msi

  create-release-on-tag:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      # 1. Download artifact MSI
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: windows-installer
          path: artifacts

      # 2. Create GitHub release
      - name: Create GitHub release for tag
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release generated by CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 3. Upload MSI to release
      - name: Upload MSI to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: artifacts/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
