name: Build Windows Application

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore UtilityDocuments.csproj

      # 4. Build the WPF application
      - name: Build the application
        run: dotnet build UtilityDocuments.csproj --configuration Release --no-restore

      # 5. Package application artifacts
      - name: Package application artifacts
        run: |
          $sourceDir = "bin/Release/net8.0-windows"
          $zipFile = "UtilityDocuments-${{ github.ref_name }}.zip"
          Compress-Archive -Path "$sourceDir\*" -DestinationPath $zipFile

      # 6. List build artifacts
      - name: List build artifacts
        run: Get-ChildItem -Recurse .\ | Select-Object FullName, Length

      # 7. Upload ZIP artifact
      - name: Upload Artifacts (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: windows-application
          path: ./*.zip

  create-release-on-tag:
    runs-on: ubuntu-latest
    needs: build-and-publish
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-application
          path: artifacts

      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: Release generated by CI
          files: artifacts/*.zip
